### ISSUE TITLE
Issues with installation and running extract

### ISSUE THREAD

**Issue by nidharap** [theblackcat102/language-models-are-knowledge-graphs-pytorch#1]
The install links in requirements.txt for spacy models dont work. I had to manually install them.

Further, after installing the models, I keep getting the following error :
Traceback (most recent call last):
  File "language-models-are-knowledge-graphs-pytorch-main/extract.py", line 3, in <module>
    from mapper import Map, deduplication
  File "language-models-are-knowledge-graphs-pytorch-main/mapper.py", line 3, in <module>
    from REL.db.generic import GenericLookup
ModuleNotFoundError: No module named 'REL'

I tried installing rel which further throws the following error : 
 pip install rel

Looking in indexes: https://pypi.org/simple
Collecting rel
  Using cached rel-0.3.1.tar.gz (9.0 kB)
    ERROR: Command errored out with exit status 1:
     command: language-models-are-knowledge-graphs-pytorch-main/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lg/cdx1ddsd2yz791mb004lbpg8dxjqm5/T/pip-install-07fd7ph9/rel_54cb449f7f8d4ed8871ce0cb5c419cc6/setup.py'"'"'; __file__='"'"'/private/var/folders/lg/cdx1ddsd2yz791mb004lbpg8dxjqm5/T/pip-install-07fd7ph9/rel_54cb449f7f8d4ed8871ce0cb5c419cc6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lg/cdx1ddsd2yz791mb004lbpg8dxjqm5/T/pip-pip-egg-info-_ir2rrqc
         cwd: /private/var/folders/lg/cdx1ddsd2yz791mb004lbpg8dxjqm5/T/pip-install-07fd7ph9/rel_54cb449f7f8d4ed8871ce0cb5c419cc6/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lg/cdx1ddsd2yz791mb004lbpg8dxjqm5/T/pip-install-07fd7ph9/rel_54cb449f7f8d4ed8871ce0cb5c419cc6/setup.py", line 1, in <module>
        from rel import __version__
      File "/private/var/folders/lg/cdx1ddsd2yz791mb004lbpg8dxjqm5/T/pip-install-07fd7ph9/rel_54cb449f7f8d4ed8871ce0cb5c419cc6/rel/__init__.py", line 2, in <module>
        from rel import override, supported_methods, initialize, read, write, timeout, signal, event, dispatch, loop, abort, init, sys, EV_PERSIST, EV_READ, EV_SIGNAL, EV_TIMEOUT, EV_WRITE
    ImportError: cannot import name 'override'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Any help is appreciated.

**Comment by ZuoHaoyu** [comment]
Hi nidharp :-)
I came across the same problem with you before. 
then I checked the code, the REL should be this REL pacakge (https://github.com/informagi/REL)
not the rel pacakge from pip.


But I came across other problem later. still with the REL pacakge.

1, **it need a folder at /document/wiki_2020/generated**
I forgot the source code regarding to this, and manually created it and it is passed.
2,  **seems a pre-defined wiki embedding db is needed in this project, but I go through the REL website and find nothing could be this., and the wikidata from REL is updated to 2019, no wiki_2020is published**
Traceback (most recent call last):
  File "extract.py", line 86, in <module>
    mapped_triplet = Map(head, relations, tail)
  File "/home/ubuntu/LAMA/language-models-are-knowledge-graphs-pytorch-main/mapper.py", line 12, in Map
    head_p_e_m = emb.wiki(str(head), 'wiki')
  File "/home/ubuntu/LAMA/language-models-are-knowledge-graphs-pytorch-main/env/lib/python3.7/site-packages/REL/db/generic.py", line 45, in wiki
    g = self.lookup_wik(mention, table_name, column_name)
  File "/home/ubuntu/LAMA/language-models-are-knowledge-graphs-pytorch-main/env/lib/python3.7/site-packages/REL/db/base.py", line 184, in lookup_wik
    {"word": w},
sqlite3.OperationalError: no such table: wiki



Looking forward of your reply.

Best wishes.

**Comment by molyswu** [comment]
import en_core_web_md
ModuleNotFoundError: No module named 'en_core_web_md'

**Comment by nidharap** [comment]
> Hi nidharp :-)
> I came across the same problem with you before.
> then I checked the code, the REL should be this REL pacakge (https://github.com/informagi/REL)
> not the rel pacakge from pip.
> 
> But I came across other problem later. still with the REL pacakge.
> 
> 1, **it need a folder at /document/wiki_2020/generated**
> I forgot the source code regarding to this, and manually created it and it is passed.
> 2, **seems a pre-defined wiki embedding db is needed in this project, but I go through the REL website and find nothing could be this., and the wikidata from REL is updated to 2019, no wiki_2020is published**
> Traceback (most recent call last):
> File "extract.py", line 86, in
> mapped_triplet = Map(head, relations, tail)
> File "/home/ubuntu/LAMA/language-models-are-knowledge-graphs-pytorch-main/mapper.py", line 12, in Map
> head_p_e_m = emb.wiki(str(head), 'wiki')
> File "/home/ubuntu/LAMA/language-models-are-knowledge-graphs-pytorch-main/env/lib/python3.7/site-packages/REL/db/generic.py", line 45, in wiki
> g = self.lookup_wik(mention, table_name, column_name)
> File "/home/ubuntu/LAMA/language-models-are-knowledge-graphs-pytorch-main/env/lib/python3.7/site-packages/REL/db/base.py", line 184, in lookup_wik
> {"word": w},
> sqlite3.OperationalError: no such table: wiki
> 
> Looking forward of your reply.
> 
> Best wishes.

Thanks for pointing that out @ZuoHaoyu . I am going to take a look at this in a couple of days and I will get back to you

**Comment by nidharap** [comment]
> import en_core_web_md
> ModuleNotFoundError: No module named 'en_core_web_md'

Try python -m spacy download en_core_web_md

**Comment by molyswu** [comment]
from REL.db.generic import GenericLookup
ModuleNotFoundError: No module named 'REL'

tried to :pip install git+https://github.com/informagi/REL,
same issues.

**Comment by molyswu** [comment]
pip install flair==0.2.6.1  in rel  ,

**Comment by nidharap** [comment]
I got it working . Just had to download the dump from the REL repo here - https://github.com/informagi/REL

Check the 'Download' section and find the corpus for the specific year - wiki 2014/2019 and then unzip it to the folder of choice. Once you do, go ahead and change the sqlite_path path in mapper.py to point to the wiki_XXXX/generated folder on line 4. 

As for flair version, if you install the REL package directly in the current virtual env created, you should be good. 

pip install git+https://github.com/informagi/REL

**Comment by aqsakhan10** [comment]
@nidharap hey Nidharap, i tried your approach to solve the REL issue , however i still get the following error 
Traceback (most recent call last):
  File "extract.py", line 88, in <module>
    mapped_triplet = Map(head, relations, tail)
  File "/Users/I535445/Desktop/Me/new/mapper.py", line 12, in Map
    head_p_e_m = emb.wiki(str(head), 'wiki')
  File "/Users/I535445/Desktop/Me/new/env1/lib/python3.8/site-packages/REL/db/generic.py", line 45, in wiki
    g = self.lookup_wik(mention, table_name, column_name)
  File "/Users/I535445/Desktop/Me/new/env1/lib/python3.8/site-packages/REL/db/base.py", line 182, in lookup_wik
    e = c.execute(
sqlite3.OperationalError: no such table: wiki

can you please help ?

**Comment by UmutAlihan** [comment]
> I got it working . Just had to download the dump from the REL repo here - https://github.com/informagi/REL
> 
> Check the 'Download' section and find the corpus for the specific year - wiki 2014/2019 and then unzip it to the folder of choice. Once you do, go ahead and change the sqlite_path path in mapper.py to point to the wiki_XXXX/generated folder on line 4.
> 
> As for flair version, if you install the REL package directly in the current virtual env created, you should be good.
> 
> pip install git+https://github.com/informagi/REL


this solves perfectly thank you very much !!
